{
 "title": "HTTP API",
 "tags": [ "httpapi-synevyr" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Throughputs rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(httpapi_request_count[$__rate_interval])",
     "legendFormat": "Requests"
    },
    {
     "expr": "rate(httpapi_success_count[$__rate_interval])",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "HTTP Request counts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "httpapi_request_count", "legendFormat": "Requests" },
    { "expr": "httpapi_success_count", "legendFormat": "Successful requests" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(httpapi_auth_error_count[$__rate_interval])",
     "legendFormat": "Authentication"
    },
    {
     "expr": "rate(httpapi_charging_error_count[$__rate_interval])",
     "legendFormat": "Charging"
    },
    {
     "expr": "rate(httpapi_interceptor_error_count[$__rate_interval])",
     "legendFormat": "Interception"
    },
    {
     "expr": "rate(httpapi_route_error_count[$__rate_interval])",
     "legendFormat": "Routing"
    },
    {
     "expr": "rate(httpapi_server_error_count[$__rate_interval])",
     "legendFormat": "Server err"
    },
    {
     "expr": "rate(httpapi_throughput_error_count[$__rate_interval])",
     "legendFormat": "Throughput"
    }
   ]
  }
 ]
}