{
 "title": "SMPP Server",
 "tags": [ "smppserver-synevyr" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Bind activity rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(smppsapi_connect_count[$__rate_interval])",
     "legendFormat": "Connect request"
    },
    {
     "expr": "rate(smppsapi_unbind_count[$__rate_interval])",
     "legendFormat": "Unbinds"
    },
    {
     "expr": "rate(smppsapi_bind_rx_count[$__rate_interval])",
     "legendFormat": "RX Bind"
    },
    {
     "expr": "rate(smppsapi_bind_trx_count[$__rate_interval])",
     "legendFormat": "TRX Bind"
    },
    {
     "expr": "rate(smppsapi_bind_tx_count[$__rate_interval])",
     "legendFormat": "TX Bind"
    }
   ]
  },
  {
   "title": "Actual bound sessions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smppsapi_bound_trx_count", "legendFormat": "Transceivers" },
    { "expr": "smppsapi_bound_tx_count", "legendFormat": "Transmitters" },
    { "expr": "smppsapi_bound_rx_count", "legendFormat": "Receivers" }
   ]
  },
  {
   "title": "Messaging activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(smppsapi_submit_sm_request_count[$__rate_interval])",
     "legendFormat": "Submit requests"
    },
    {
     "expr": "rate(smppsapi_submit_sm_count[$__rate_interval])",
     "legendFormat": "Accepted submits"
    },
    {
     "expr": "rate(smppsapi_deliver_sm_count[$__rate_interval])",
     "legendFormat": "Delivers"
    },
    {
     "expr": "rate(smppsapi_data_sm_count[$__rate_interval])",
     "legendFormat": "DataSm's"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(smppsapi_throttling_error_count[$__rate_interval])",
     "legendFormat": "Throttling"
    },
    {
     "expr": "rate(smppsapi_interceptor_error_count[$__rate_interval])",
     "legendFormat": "Interception"
    },
    {
     "expr": "rate(smppsapi_other_submit_error_count[$__rate_interval])",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Enquirelink activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "rate(smppsapi_elink_count[$__rate_interval])",
     "legendFormat": "EnquireLinks"
    }
   ]
  }
 ]
}