version: "3"

services:
  redis:
    image: redis:7.0.5-alpine
    restart: always
    volumes:
      - redis:/data
    networks:
      - jasmin
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      retries: 3
      timeout: 5s

  rabbit-mq:
    image: rabbitmq:3.11.3-alpine
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - jasmin
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3

  jasmin:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.extra.alpine
    image: jasmin-extra:alpine
    restart: always
    ports:
      - '${FORWARD_JASMIN_SMPP_PORT:-2775}:2775'
      - '${FORWARD_JASMIN_CLI_PORT:-8990}:8990'
      - '${FORWARD_JASMIN_HTTP_PORT:-1401}:1401'
      - '${FORWARD_JASMIN_RESTAPI_PORT:-1402}:1402'
    volumes:
      - jasmin_config:/etc/jasmin
      - jasmin_store:/etc/jasmin/store
      - jasmin_logs:/var/log/jasmin
    tmpfs:
      - /tmp
    networks:
      - jasmin
    depends_on:
      # postgres:
      #   condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
    environment:
      REDIS_CLIENT_HOST: ${REDIS_CLIENT_HOST:-redis}
      REDIS_CLIENT_PORT: ${REDIS_CLIENT_PORT:-6379}
      AMQP_BROKER_HOST: ${AMQP_BROKER_HOST:-rabbit-mq}
      AMQP_BROKER_PORT: ${AMQP_BROKER_PORT:-5672}
      ENABLE_RESTAPI: ${ENABLE_RESTAPI:-0}
      ENABLE_SMS_LOGGER: ${ENABLE_SMS_LOGGER:-0}
      DB_TYPE_MYSQL: ${DB_TYPE_MYSQL:-1}
      DB_HOST: '${DB_HOST:-127.0.0.1}'
      DB_DATABASE: '${DB_DATABASE:-jasmin}'
      DB_TABLE: '${DB_TABLE:-submit_log}'
      DB_USER: '${DB_USERNAME:-jasmin}'
      DB_PASS: '${DB_PASSWORD:-jadmin}'

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    # ports:
    #   - '${FORWARD_MYSQL_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-jadmin}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-jasmin}'
      MYSQL_USER: '${DB_USERNAME:-jasmin}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-jadmin}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - jasmin
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-jadmin}" ]
      retries: 3
      timeout: 5s

  # postgres:
  #   image: postgres:alpine
  #   container_name: PostgreSQL
  #   restart: always
  #   ports:
  #     - '${FORWARD_POSTGRESQL_DB_PORT:-5432}:5432'
  #   environment:
  #     POSTGRES_USER: '${DB_USERNAME:-jasmin}'
  #     POSTGRES_PASSWORD: '${DB_PASSWORD:-jadmin}'
  #     POSTGRES_DB: '${DB_DATABASE:-jasmin}'
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   networks:
  #     - jasmin
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "sh -c 'pg_isready -U ${DB_USERNAME:-jasmin} -d ${DB_DATABASE:-jasmin}'"
  #       ]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3

networks:
  jasmin:
    driver: bridge
volumes:
  jasmin_config: {}
  jasmin_store: {}
  jasmin_logs: {}
  mysql: {}
  # postgres: {}
  rabbitmq: {}
  redis: {}
