"""jCli transcript scenarios, one per JCLI_MATRIX row (or group of rows).

A scenario is a whole session. Mutations are part of it on purpose: replaying
the same input lines against the Go console must produce the same bytes, which
only proves anything if the state the later `list`/`show` lines read was built
by the earlier lines in the same transcript.

`authentication` False skips the Username/Password exchange (the frozen
`JCliConfig.authentication` switch), which keeps the non-auth scenarios short.
"""

# The oracle's default console credentials (JCliConfig.admin_username and the
# md5 of 'jclipwd' it ships as admin_password).
USERNAME = 'jcliadmin'
PASSWORD = 'jclipwd'

SCENARIOS = [
    {
        'id': 'J-001-auth-success',
        'title': 'connect, authenticate, quit',
        'authentication': True,
        'inputs': [USERNAME, PASSWORD, 'quit'],
    },
    {
        'id': 'J-001-auth-failure',
        'title': 'wrong password, then a successful retry',
        'authentication': True,
        'inputs': [USERNAME, 'wrong-password', USERNAME, PASSWORD, 'quit'],
    },
    {
        'id': 'J-002-help',
        'title': 'help, help <cmd>, help on an unknown command',
        'authentication': False,
        'inputs': ['help', 'help user', 'help nosuchcommand', 'nosuchcommand', 'quit'],
    },
    {
        'id': 'J-002-completion',
        'title': 'TAB completion on a command prefix and on nothing',
        'authentication': False,
        # A trailing TAB is sent as typed, with no RETURN (see the harness).
        'inputs': ['mt\t', '', 'nosuch\t', '', '\t', '', 'quit'],
    },
    {
        'id': 'J-002-help-commands',
        'title': 'help for every registered command',
        'authentication': False,
        # The per-command help is optparse's own rendering (usage line, option
        # column, continuation wrapping). Capturing it verbatim beats
        # reimplementing optparse's layout rules in Go and hoping they match.
        'inputs': [
            'help persist', 'help load', 'help user', 'help group', 'help filter',
            'help mointerceptor', 'help mtinterceptor', 'help morouter',
            'help mtrouter', 'help smppccm', 'help httpccm', 'help stats',
            'help quit', 'help help',
            'quit',
        ],
    },
    {
        'id': 'J-003-group',
        'title': 'group add/list/enable/disable/remove',
        'authentication': False,
        'inputs': [
            'group -l',
            'group -a', 'gid gid1', 'ok',
            'group -l',
            'group -d gid1',
            'group -l',
            'group -e gid1',
            'group -l',
            'group -r gid1',
            'group -l',
            'quit',
        ],
    },
    {
        'id': 'J-004-user',
        'title': 'user add/list/show/update/remove',
        'authentication': False,
        'inputs': [
            'group -a', 'gid gid1', 'ok',
            'user -l',
            'user -a', 'username u1', 'password pwd1', 'gid gid1', 'uid uid1', 'ok',
            'user -l',
            'user -s uid1',
            'user -u uid1', 'username u2', 'ko',
            'user -u uid1', 'mt_messaging_cred quota balance 50.0', 'ok',
            'user -s uid1',
            'user -d uid1',
            'user -e uid1',
            'user -r uid1',
            'user -l',
            'quit',
        ],
    },
    {
        'id': 'J-005-user-credentials',
        'title': 'user credential, quota and default fields',
        'authentication': False,
        'inputs': [
            'group -a', 'gid gid1', 'ok',
            'user -a',
            'username u1', 'password pwd1', 'gid gid1', 'uid uid1',
            'mt_messaging_cred authorization http_send True',
            'mt_messaging_cred authorization http_dlr_method False',
            'mt_messaging_cred valuefilter dst_addr ^32.*',
            'mt_messaging_cred defaultvalue src_addr 1234',
            'mt_messaging_cred quota balance 100.2',
            'mt_messaging_cred quota sms_count 10',
            'mt_messaging_cred quota early_percent 10',
            'smpps_cred authorization bind True',
            'smpps_cred quota max_bindings 2',
            'ok',
            'user -s uid1',
            'quit',
        ],
    },
    {
        'id': 'J-005-user-invalid',
        'title': 'invalid key and invalid value inside an interactive session',
        'authentication': False,
        'inputs': [
            'user -a',
            'nosuchkey value',
            'mt_messaging_cred quota balance not-a-number',
            'ko',
            'user -l',
            'quit',
        ],
    },
    {
        'id': 'J-007-filter',
        'title': 'filter add/list/show/remove across filter types',
        'authentication': False,
        'inputs': [
            'filter -l',
            'filter -a', 'fid f1', 'type TransparentFilter', 'ok',
            'filter -a', 'fid f2', 'type DestinationAddrFilter', 'destination_addr ^32.*', 'ok',
            'filter -a', 'fid f3', 'type ShortMessageFilter', 'short_message .*hello.*', 'ok',
            'filter -l',
            'filter -s f2',
            'filter -r f2',
            'filter -l',
            'quit',
        ],
    },
    {
        'id': 'J-008-morouter',
        'title': 'morouter add/list/show/remove/flush',
        'authentication': False,
        'inputs': [
            'httpccm -a', 'cid http1', 'url http://127.0.0.1/mo', 'method GET', 'ok',
            'filter -a', 'fid f1', 'type TransparentFilter', 'ok',
            'morouter -l',
            'morouter -a', 'type DefaultRoute', 'connector http(http1)', 'ok',
            'morouter -a', 'type StaticMORoute', 'order 10', 'filters f1', 'connector http(http1)', 'ok',
            'morouter -l',
            'morouter -s 10',
            'morouter -r 10',
            'morouter -l',
            'morouter -f',
            'morouter -l',
            'quit',
        ],
    },
    {
        'id': 'J-009-mtrouter',
        'title': 'mtrouter add/list/show/remove/flush with rates',
        'authentication': False,
        'inputs': [
            'smppccm -a', 'cid smpp1', 'logfile /tmp/jasmin-oracle-smpp1.log', 'ok',
            'filter -a', 'fid f1', 'type TransparentFilter', 'ok',
            'mtrouter -l',
            'mtrouter -a', 'type DefaultRoute', 'connector smppc(smpp1)', 'rate 0.0', 'ok',
            'mtrouter -a', 'type StaticMTRoute', 'order 10', 'filters f1', 'connector smppc(smpp1)', 'rate 1.5', 'ok',
            'mtrouter -l',
            'mtrouter -s 10',
            'mtrouter -r 10',
            'mtrouter -l',
            'mtrouter -f',
            'mtrouter -l',
            'quit',
        ],
    },
    {
        'id': 'J-010-mointerceptor',
        'title': 'mointerceptor add/list/show/remove/flush',
        'authentication': False,
        'inputs': [
            'filter -a', 'fid f1', 'type TransparentFilter', 'ok',
            'mointerceptor -l',
            'mointerceptor -a', 'type DefaultInterceptor', 'script python3({SCRIPT})', 'ok',
            'mointerceptor -a', 'type StaticMOInterceptor', 'order 10', 'filters f1',
            'script python3({SCRIPT})', 'ok',
            'mointerceptor -l',
            'mointerceptor -s 10',
            'mointerceptor -r 10',
            'mointerceptor -f',
            'mointerceptor -l',
            'quit',
        ],
    },
    {
        'id': 'J-011-mtinterceptor',
        'title': 'mtinterceptor add/list/show/remove/flush',
        'authentication': False,
        'inputs': [
            'filter -a', 'fid f1', 'type TransparentFilter', 'ok',
            'mtinterceptor -l',
            'mtinterceptor -a', 'type DefaultInterceptor', 'script python3({SCRIPT})', 'ok',
            'mtinterceptor -a', 'type StaticMTInterceptor', 'order 10', 'filters f1',
            'script python3({SCRIPT})', 'ok',
            'mtinterceptor -l',
            'mtinterceptor -s 10',
            'mtinterceptor -r 10',
            'mtinterceptor -f',
            'mtinterceptor -l',
            'quit',
        ],
    },
    {
        'id': 'J-012-smppccm',
        'title': 'smppccm add/list/show/update/remove',
        'authentication': False,
        'inputs': [
            'smppccm -l',
            'smppccm -a', 'cid smpp1', 'host 127.0.0.1', 'port 2775',
            'username u1', 'password p1', 'bind transceiver',
            'logfile /tmp/jasmin-oracle-smpp1.log', 'ok',
            'smppccm -l',
            'smppccm -s smpp1',
            'smppccm -u smpp1', 'port 2776', 'ok',
            'smppccm -s smpp1',
            'smppccm -r smpp1',
            'smppccm -l',
            'quit',
        ],
    },
    {
        'id': 'J-013-httpccm',
        'title': 'httpccm add/list/show/remove',
        'authentication': False,
        'inputs': [
            'httpccm -l',
            'httpccm -a', 'cid http1', 'url http://127.0.0.1/mo', 'method GET', 'ok',
            'httpccm -l',
            'httpccm -s http1',
            'httpccm -r http1',
            'httpccm -l',
            'quit',
        ],
    },
    {
        'id': 'J-014-stats',
        'title': 'stats users/user/smppcs/smppc/smpps/httpapi',
        'authentication': False,
        'inputs': [
            'group -a', 'gid gid1', 'ok',
            'user -a', 'username u1', 'password pwd1', 'gid gid1', 'uid uid1', 'ok',
            'smppccm -a', 'cid smpp1', 'logfile /tmp/jasmin-oracle-smpp1.log', 'ok',
            'stats --users',
            'stats --user uid1',
            'stats --smppcs',
            'stats --smppc smpp1',
            'stats --smppsapi',
            'stats --httpapi',
            'quit',
        ],
    },
    {
        'id': 'J-015-persist-load',
        'title': 'persist and load, default and named profile',
        'authentication': False,
        'inputs': [
            'group -a', 'gid gid1', 'ok',
            'persist',
            'load',
            'persist -p testprofile',
            'load -p testprofile',
            'load -p nosuchprofile',
            'group -l',
            'quit',
        ],
    },
]
