package core

import (
	"context"
	"errors"
	"time"

	"github.com/pumpitspace/synevyr/internal/core/billing"
	"github.com/pumpitspace/synevyr/internal/core/tlv"
	"github.com/pumpitspace/synevyr/internal/transport/smppwire"
)

var (
	ErrAuthentication   = errors.New("authentication failed")
	ErrNoLiveConnector  = errors.New("no live connector")
	ErrQuotaExceeded    = errors.New("quota exceeded")
	ErrFilterRejected   = errors.New("request rejected by filters")
	ErrInvalidParameter = errors.New("invalid parameter")
	// ErrThroughputExceeded is the user's per-second submit ceiling being hit.
	// Distinct from ErrQuotaExceeded (balance / submit_sm_count) because the
	// two map to different front-door responses and different counters.
	ErrThroughputExceeded = errors.New("user throughput exceeded")
)

// Authenticator verifies that a user and its group are enabled and that the
// supplied credentials are valid.
type Authenticator interface {
	Authenticate(ctx context.Context, username, password string) error
}

// DigestAuthenticator verifies a previously authenticated asynchronous request
// without retaining its plaintext password. The digest is the SHA-256 proof
// captured when the REST batch was accepted; implementations must compare it
// in constant time and still enforce the user's and group's current enabled
// state.
type DigestAuthenticator interface {
	AuthenticateDigest(ctx context.Context, username string, digest []byte) error
}

// BalanceSnapshot keeps decimal values as strings so the core never loses
// precision. A nil value represents the legacy unlimited quota.
type BalanceSnapshot struct {
	Balance  *string
	SMSCount *string
}

type BalanceReader interface {
	Balance(ctx context.Context, username string) (BalanceSnapshot, error)
}

type RateQuote struct {
	UnitRate      float64
	SubmitSMCount int
}

type RateReader interface {
	Rate(ctx context.Context, username, destination string) (RateQuote, error)
}

type SubmitRequest struct {
	// MessageID is normally empty and generated by SubmitService. Trusted
	// durable ingress may supply a stable UUID so recovery after a process crash
	// can observe an already-admitted submit and return it without charging or
	// publishing it twice.
	MessageID      string
	Username       string
	Password       string
	Destination    string
	Content        string
	HexContent     string
	From           string
	Coding         int
	Priority       int
	SDT            *time.Time
	ValidityPeriod *time.Duration
	DLR            bool
	DLRUrl         string
	DLRLevel       int
	DLRMethod      string
	Tags           []string
	// CustomTLVs is the tlv.Normalize output for the request's custom_tlvs
	// argument, in caller order (wire order). Types stay unresolved here;
	// connector rules apply them at submit time, matching the legacy listener.
	CustomTLVs []tlv.TLV
	// SourceConnector names the ingress: "httpapi" (default when empty) or
	// "smppsapi". It flows to the AMQP envelope's source_connector header and
	// the DLR record's sc field, so a receipt correlates back to the right leg.
	SourceConnector string
	// SMPPSOrigin is set only for a submit that arrived over an SMPP bind. It
	// carries what the DLR record needs to route a later receipt back to that
	// bind; nil on the HTTP path, which registers its callback URL instead.
	SMPPSOrigin *SMPPSOrigin
	// ESMClass is the ESME's own esm_class byte, set only on the SMPPs path.
	// Its UDHI bit is load bearing: it declares that short_message opens with a
	// binary User Data Header, which must not be re-encoded or re-segmented and
	// must still be flagged as a UDH on the outbound PDU.
	ESMClass byte
	// SMPPSubmit is the original ESME submit_sm body after credential-default
	// application. The SMPPs path preserves its mandatory PDU fields and
	// standard optionals across routing; nil for HTTP-originated submits.
	SMPPSubmit *smppwire.SubmitSMBody
	// TrustedManagerSubmit is set only by the authenticated private PB facade
	// for SMPPClientManagerPB.perspective_submit_sm. That frozen method receives
	// an already-routed PDU and an already-applied early bill, then publishes it
	// directly to submit.sm.<cid>. Keeping the override explicit prevents the
	// public HTTP/SMPP ingress paths from bypassing routing or billing.
	TrustedManagerSubmit *TrustedManagerSubmit
}

// TrustedManagerSubmit carries the inputs that the frozen Router/HTTP layer
// handed to SMPPClientManagerPB after route selection and early charging.
// The durable Go submit transaction still owns message-id generation,
// idempotent admission, envelope publication, late billing and DLR storage.
type TrustedManagerSubmit struct {
	ConnectorID  string
	BillID       string
	Bill         billing.Bill
	HasBill      bool
	DLRConnector string
	// ValidityPeriod is the frozen absolute AMQP expiration header
	// (YYYY-MM-DD HH:MM:SS). It is distinct from the submit_sm PDU's own
	// validity_period field, which remains in each raw PDU.
	ValidityPeriod string
	// SubmitSMChain is the ordered frozen SubmitSM.nextPdu chain. The first
	// entry is also SubmitRequest.SMPPSubmit; keeping the complete list here
	// prevents linked SAR/UDH parts from being silently truncated at the PB
	// translation boundary.
	SubmitSMChain []*smppwire.SubmitSMBody
}

// esmClassUDHI is the GSM UDH-indicator bit of esm_class (SMPP 3.4 §5.2.12).
const esmClassUDHI byte = 0x40

// HasUDHI reports whether the submitting ESME declared a User Data Header.
func (r SubmitRequest) HasUDHI() bool { return r.ESMClass&esmClassUDHI != 0 }

// SMPPSOrigin is the submitting bind's identity and addressing, as the ESME
// sent them. These do not come from the connector defaults: a receipt has to be
// addressed the way the original submit was, not the way the outbound leg was.
type SMPPSOrigin struct {
	SystemID string
	// TON/NPI are the legacy enum *names* ("AddrTon.INTERNATIONAL"), not the
	// numeric values, because that is what the frozen Redis record stores.
	SourceAddrTON      string
	SourceAddrNPI      string
	DestinationAddrTON string
	DestinationAddrNPI string
	// RegisteredDelivery is the RegisteredDeliveryReceipt enum name the ESME
	// asked for; legacy stores it as rd_receipt.
	RegisteredDelivery string
}

type Submitter interface {
	Submit(ctx context.Context, request SubmitRequest) (messageID string, err error)
}
